version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.2.115
      KAFKA_ZOOKEEPER_CONNECT: 172.16.2.115:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: 172.16.2.115
    ports:
      - "19002:9000"